package com.wanlitong.jmetrics.model;

import java.util.Date;

public class Execution {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.execution_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long executionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.task_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.start_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.end_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column execution.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.execution_id
     *
     * @return the value of execution.execution_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getExecutionId() {
        return executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.execution_id
     *
     * @param executionId the value for execution.execution_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.job_id
     *
     * @return the value of execution.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.job_id
     *
     * @param jobId the value for execution.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.task_id
     *
     * @return the value of execution.task_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.task_id
     *
     * @param taskId the value for execution.task_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.name
     *
     * @return the value of execution.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.name
     *
     * @param name the value for execution.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.status
     *
     * @return the value of execution.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.status
     *
     * @param status the value for execution.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.start_time
     *
     * @return the value of execution.start_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.start_time
     *
     * @param startTime the value for execution.start_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.end_time
     *
     * @return the value of execution.end_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.end_time
     *
     * @param endTime the value for execution.end_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.create_time
     *
     * @return the value of execution.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.create_time
     *
     * @param createTime the value for execution.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column execution.update_time
     *
     * @return the value of execution.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column execution.update_time
     *
     * @param updateTime the value for execution.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}