package com.wanlitong.jmetrics.model;

import java.util.Date;

public class Job {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.system_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_id
     *
     * @return the value of job.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_id
     *
     * @param jobId the value for job.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.name
     *
     * @return the value of job.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.name
     *
     * @param name the value for job.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.description
     *
     * @return the value of job.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.description
     *
     * @param description the value for job.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.status
     *
     * @return the value of job.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.status
     *
     * @param status the value for job.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.system_id
     *
     * @return the value of job.system_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.system_id
     *
     * @param systemId the value for job.system_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.create_time
     *
     * @return the value of job.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.create_time
     *
     * @param createTime the value for job.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.update_time
     *
     * @return the value of job.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.update_time
     *
     * @param updateTime the value for job.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}