package com.wanlitong.jmetrics.model;

import java.util.Date;

public class Metric {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.metric_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long metricId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.system_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long systemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.table
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.field_name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.field_type
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String fieldType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column metric.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.metric_id
     *
     * @return the value of metric.metric_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getMetricId() {
        return metricId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.metric_id
     *
     * @param metricId the value for metric.metric_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setMetricId(Long metricId) {
        this.metricId = metricId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.name
     *
     * @return the value of metric.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.name
     *
     * @param name the value for metric.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.description
     *
     * @return the value of metric.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.description
     *
     * @param description the value for metric.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.system_id
     *
     * @return the value of metric.system_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.system_id
     *
     * @param systemId the value for metric.system_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.table
     *
     * @return the value of metric.table
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.table
     *
     * @param table the value for metric.table
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.field_name
     *
     * @return the value of metric.field_name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.field_name
     *
     * @param fieldName the value for metric.field_name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.field_type
     *
     * @return the value of metric.field_type
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.field_type
     *
     * @param fieldType the value for metric.field_type
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType == null ? null : fieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.create_time
     *
     * @return the value of metric.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.create_time
     *
     * @param createTime the value for metric.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column metric.update_time
     *
     * @return the value of metric.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column metric.update_time
     *
     * @param updateTime the value for metric.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}