package com.wanlitong.jmetrics.model;

import java.util.Date;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Long jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.schedule_rate
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Integer scheduleRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.schedule_unit
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Byte scheduleUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.scheduled_count
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Integer scheduledCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_id
     *
     * @return the value of task.task_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_id
     *
     * @param taskId the value for task.task_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.job_id
     *
     * @return the value of task.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.job_id
     *
     * @param jobId the value for task.job_id
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.name
     *
     * @return the value of task.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.name
     *
     * @param name the value for task.name
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.description
     *
     * @return the value of task.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.description
     *
     * @param description the value for task.description
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.schedule_rate
     *
     * @return the value of task.schedule_rate
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Integer getScheduleRate() {
        return scheduleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.schedule_rate
     *
     * @param scheduleRate the value for task.schedule_rate
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setScheduleRate(Integer scheduleRate) {
        this.scheduleRate = scheduleRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.schedule_unit
     *
     * @return the value of task.schedule_unit
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Byte getScheduleUnit() {
        return scheduleUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.schedule_unit
     *
     * @param scheduleUnit the value for task.schedule_unit
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setScheduleUnit(Byte scheduleUnit) {
        this.scheduleUnit = scheduleUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.scheduled_count
     *
     * @return the value of task.scheduled_count
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Integer getScheduledCount() {
        return scheduledCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.scheduled_count
     *
     * @param scheduledCount the value for task.scheduled_count
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setScheduledCount(Integer scheduledCount) {
        this.scheduledCount = scheduledCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.update_time
     *
     * @return the value of task.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.update_time
     *
     * @param updateTime the value for task.update_time
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}