package com.wanlitong.jmetrics.mapper;

import com.wanlitong.jmetrics.model.Execution;
import java.util.List;

public interface ExecutionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int deleteByPrimaryKey(Long executionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int insert(Execution record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    Execution selectByPrimaryKey(Long executionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    List<Execution> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table execution
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int updateByPrimaryKey(Execution record);
}