package com.wanlitong.jmetrics.mapper;

import com.wanlitong.jmetrics.model.Job;
import java.util.List;

public interface JobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int insert(Job record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    Job selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    List<Job> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int updateByPrimaryKey(Job record);
}