package com.wanlitong.jmetrics.mapper;

import com.wanlitong.jmetrics.model.Metric;
import java.util.List;

public interface MetricMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int deleteByPrimaryKey(Long metricId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int insert(Metric record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    Metric selectByPrimaryKey(Long metricId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    List<Metric> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table metric
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int updateByPrimaryKey(Metric record);
}