package com.wanlitong.jmetrics.mapper;

import com.wanlitong.jmetrics.model.MonitoredSystem;
import java.util.List;

public interface MonitoredSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitored_system
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int deleteByPrimaryKey(Long systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitored_system
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int insert(MonitoredSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitored_system
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    MonitoredSystem selectByPrimaryKey(Long systemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitored_system
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    List<MonitoredSystem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitored_system
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int updateByPrimaryKey(MonitoredSystem record);
}