package com.wanlitong.jmetrics.mapper;

import com.wanlitong.jmetrics.model.Task;
import java.util.List;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    Task selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    List<Task> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Wed Oct 14 19:13:54 CST 2015
     */
    int updateByPrimaryKey(Task record);
}